[package]
name = "serde_roundtrip_derive"
version = "0.0.1"
authors = ["ajeffrey@mozilla.com"]

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
syn = {version = "0.11", features = ["fold"]}
quote = "0.3"